spring:
  application:
    name: Journal App

  data:
    mongodb:
      uri:
      database: journaldb
      auto-index-creation: true

  main:
      allow-circular-references : true

server:
  servlet:
    context-path: /journal
  port: 8081